### ISSUE TITLE
推不了代码，新建 pull request 和 新建分支再推 都不行。能拉不能推

### ISSUE THREAD

**Issue by waconde** [gzzyj/Java-develop-document#2]
![image](https://user-images.githubusercontent.com/28390161/133458540-1d6ef3ba-00d9-486f-bf6c-c927b1637fcc.png)

![image](https://user-images.githubusercontent.com/28390161/133458388-281619a8-aed4-4fa9-a9dd-81df9828a936.png)

**Comment by gzzyj** [comment]
git pull 一下看报什么错误？

**Comment by waconde** [comment]
看看这里配的怎么样
![image](https://user-images.githubusercontent.com/28390161/133459432-7d603ead-705a-4eab-a34b-aa1a84ffede4.png)

**Comment by waconde** [comment]
pull 没问题
idea自己拉：
![image](https://user-images.githubusercontent.com/28390161/133459777-834c6aff-186e-4fa5-bbfd-6a65eaa5d361.png)
命令行拉：
![image](https://user-images.githubusercontent.com/28390161/133459876-e4432e7f-f0d6-4bf1-b849-3f7ead55b880.png)

**Comment by gzzyj** [comment]
我把你加进协作者里了

**Comment by gzzyj** [comment]
> pull 没问题
> idea自己拉：
> ![image](https://user-images.githubusercontent.com/28390161/133459777-834c6aff-186e-4fa5-bbfd-6a65eaa5d361.png)
> 命令行拉：
> ![image](https://user-images.githubusercontent.com/28390161/133459876-e4432e7f-f0d6-4bf1-b849-3f7ead55b880.png)

再试试

**Comment by waconde** [comment]
可以推了，就那个协作者设置，不过好像说是 7 天有效期
